name: Export and Publish to itch.io

on:
  push:
    branches:
      - main

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Godot Export
        id: export
        uses: firebelley/godot-export@v7.0.0 
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.5.1-stable/Godot_v4.5.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.5.1-stable/Godot_v4.5.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          cache: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to itch.io
        uses: Ayowel/butler-to-itch@v1.0.0
        with:
          butler_key: ${{ secrets.BUTLER_CREDENTIALS }}
          itch_user: tudormacovei
          itch_game: wintergameproject
          version: ${{ github.sha }}
          files: |
            ${{ steps.export.outputs.archive_directory }}/*.zip